#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: stleroux

"""
import cvxpy as cp

"""
Problem 1: Automotive Firm (redo)
"""

x = cp.Variable(3, nonneg  = True)

#contraints are of form x/y = z... 
#the following array is a linear adjustment of the constraints inequality

constraints = []
constraints.append((18*x[0]+29*x[1]+38*x[2]) >= 30*(x[0]+x[1]+x[2]))
constraints.append(x[0]<=600000) #demand constraint x1
constraints.append(x[1]<=800000) #demand constraint x2
constraints.append(x[2]<=700000) #demand constraint x3

obj_func= 600*x[0]+460*x[1]+320*x[2]

problem = cp.Problem(cp.Maximize(obj_func), constraints)
problem.solve(solver=cp.GUROBI,verbose = False)
# "verbose parameter determines showing/not showing the output"

print(f"Objective function (P1): {obj_func}")
print(f"Optimal solutions (P1): {x.value}")

"""
Problem 2: Investment Problem (redo)
"""

